language: julia
os:
  - osx
  - linux
julia:
  - 0.5
  - 0.6
  - nightly
notifications:
email: false
after_success:
  - julia -e 'cd(Pkg.dir("LinearLeastSquares")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
